/* generated by scripts/export_demo_baselines.py — do not edit */
var REVOICE_VERSION = {
  "revoice": "0.1.11",
  "voicemetric": "0.5.0",
  "voicemetric_signature": "bfd1b0992fc8",
  "rubric": "1.0.0"
};
